export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"
export const USER_DETAILS = "USER_DETAILS"
//CLASSROOM

export const CURRENT_CLASS = "CURRENT_CLASS"
export const CURRENT_PAGE = "CURRENT_PAGE"